version: '3'

services:
  web:
    build: docker/web
    image: sazzabi/web
    container_name: web
    env_file:
      - .env
    volumes:
      - .:${PROJECT_DIR}
    working_dir: ${PROJECT_DIR}
    ports:
      - 8080:80
    depends_on:
      - php

  php:
    build: docker/php
    image: sazzabi/php
    container_name: php
    env_file:
      - .env
    volumes:
      - .:${PROJECT_DIR}
    working_dir: ${PROJECT_DIR}

  haproxy:
    build: docker/haproxy
    image: sazzabi/haproxy
    container_name: haproxy
    env_file:
      - .env
    links:
      - varnish
    ports:
      - 80:80

  varnish:
    build: docker/varnish
    image: sazzabi/varnish
    container_name: varnish
    env_file:
      - .env
    links:
      - web
    ports:
      - 8000:8000
